"""Curated official sources + fact cards. Not the entire internet."""

SOURCES = [
    {"topic": "autogen", "title": "AgentChat termination",
     "url": "https://microsoft.github.io/autogen/0.4.4/user-guide/agentchat-user-guide/tutorial/termination.html"},
    {"topic": "autogen", "title": "Selector Group Chat",
     "url": "https://microsoft.github.io/autogen/stable/user-guide/agentchat-user-guide/selector-group-chat.html"},
    {"topic": "autogen", "title": "Teams RoundRobin vs Selector vs Swarm",
     "url": "https://www.mintlify.com/microsoft/autogen/agentchat/teams"},
    {"topic": "autogen", "title": "SelectorGroupChat reference candidate_func",
     "url": "https://microsoft.github.io/autogen/0.5.6/reference/python/autogen_agentchat.teams.html"},
    {"topic": "autogen", "title": "Magentic-One",
     "url": "https://microsoft.github.io/autogen/stable/user-guide/agentchat-user-guide/magentic-one.html"},
    {"topic": "autogen", "title": "v0.2 to v0.4 migration",
     "url": "https://microsoft.github.io/autogen/0.4.0/user-guide/agentchat-user-guide/migration-guide.html"},
    {"topic": "autogen", "title": "AutoGen GitHub",
     "url": "https://github.com/microsoft/autogen"},
    {"topic": "crewai", "title": "HITL workflows",
     "url": "https://docs.crewai.com/en/learn/human-in-the-loop"},
    {"topic": "crewai", "title": "Human feedback in Flows",
     "url": "https://docs.crewai.com/en/learn/human-feedback-in-flows"},
    {"topic": "crewai", "title": "Resume API",
     "url": "https://docs.crewai.com/en/api-reference/resume.md"},
    {"topic": "crewai", "title": "Execution hooks",
     "url": "https://docs.crewai.com/v1.15.18/en/learn/execution-hooks"},
    {"topic": "crewai", "title": "Frontend HITL",
     "url": "https://docs.crewai.com/v1.15.16/en/guides/frontend/human-in-the-loop"},
    {"topic": "langgraph", "title": "Interrupts",
     "url": "https://docs.langchain.com/oss/python/langgraph/interrupts"},
    {"topic": "langgraph", "title": "interrupt() reference",
     "url": "https://reference.langchain.com/python/langgraph/types/interrupt"},
    {"topic": "langgraph", "title": "Persistence checkpointer vs store",
     "url": "https://docs.langchain.com/oss/python/langgraph/persistence"},
    {"topic": "langgraph", "title": "Checkpointers",
     "url": "https://docs.langchain.com/oss/python/langgraph/checkpointers"},
    {"topic": "langgraph", "title": "Checkpoint reference",
     "url": "https://reference.langchain.com/python/langgraph/checkpoints"},
    {"topic": "langgraph", "title": "Graph API add_messages",
     "url": "https://docs.langchain.com/oss/python/langgraph/graph-api"},
    {"topic": "langgraph", "title": "add_messages",
     "url": "https://reference.langchain.com/python/langgraph/graph/message/add_messages"},
    {"topic": "langgraph", "title": "MessagesState",
     "url": "https://reference.langchain.com/python/langgraph/graph/message/MessagesState"},
    {"topic": "langgraph", "title": "Add memory RemoveMessage",
     "url": "https://docs.langchain.com/oss/python/langgraph/add-memory"},
    {"topic": "langgraph", "title": "Human-in-the-loop JS",
     "url": "https://docs.langchain.com/oss/javascript/langchain/human-in-the-loop"},
    {"topic": "langgraph", "title": "interrupt blog",
     "url": "https://www.langchain.com/blog/making-it-easier-to-build-human-in-the-loop-agents-with-interrupt"},
    {"topic": "langgraph", "title": "add_messages source",
     "url": "https://github.com/langchain-ai/langgraph/blob/main/libs/langgraph/langgraph/graph/message.py"},
    {"topic": "langgraph", "title": "checkpoint package",
     "url": "https://github.com/langchain-ai/langgraph/tree/main/libs/checkpoint"},
    {"topic": "oversight", "title": "Oversight Has a Capacity arXiv:2606.08919",
     "url": "https://arxiv.org/abs/2606.08919"},
    {"topic": "xai", "title": "xAI docs",
     "url": "https://docs.x.ai/overview.md"},
    {"topic": "xai", "title": "Grok 4.6",
     "url": "https://x.ai/docs/developers/models/grok-4.6"},
    {"topic": "xai", "title": "Quickstart",
     "url": "https://x.ai/docs/developers/quickstart"},
    {"topic": "xai", "title": "API keys",
     "url": "https://console.x.ai/team/default/api-keys"},
    {"topic": "xai", "title": "xAI API",
     "url": "https://x.ai/api"},
]

CARDS = [
    {"id": "ag-term", "topic": "autogen", "tags": "termination maxmessage textmention or and delta",
     "fact": "AutoGen TerminationCondition on the delta since last check. Combine with | (OR) and & (AND). MaxMessageTermination counts agent+task messages. Team calls it once per agent response."},
    {"id": "ag-rr", "topic": "autogen", "tags": "roundrobin groupchat turns fixed",
     "fact": "RoundRobinGroupChat: fixed speaker order. Use when stages must run in sequence. Cheap and testable. Wastes turns if a role is not needed."},
    {"id": "ag-sel", "topic": "autogen", "tags": "selector llm speaker candidate_func selector_func allow_repeated",
     "fact": "SelectorGroupChat: LLM picks next speaker from names+descriptions. selector_func returning a name bypasses the model; None falls back to LLM. candidate_func only filters names and is ignored if selector_func is set. Empty candidate list raises ValueError. allow_repeated_speaker default False; with False, issue #7471 can livelock — always add MaxMessageTermination."},
    {"id": "ag-mag", "topic": "autogen", "tags": "magentic one web file orchestrator",
     "fact": "Magentic-One is an AgentChat team (MagenticOneGroupChat) for open-ended web/file tasks: orchestrator + WebSurfer + FileSurfer + coder. Code exec should go through approval_func."},
    {"id": "crew-hitl", "topic": "crewai", "tags": "hitl webhook resume is_approve human_input",
     "fact": "CrewAI HITL: task human_input=True pauses. Resume POST needs execution_id, task_id, human_feedback, is_approve. Webhook URLs must be sent again on resume. is_approve false retries the task."},
    {"id": "crew-flow", "topic": "crewai", "tags": "human_feedback pending provider slack",
     "fact": "@human_feedback on Flows can block on console or raise HumanFeedbackPending via a provider, then Flow.from_pending(id).resume(feedback)."},
    {"id": "crew-hook", "topic": "crewai", "tags": "pre_tool_call hook aborted approval",
     "fact": "CrewAI @on(PRE_TOOL_CALL) can abort dangerous tools or request_human_input before send_email/make_payment."},
    {"id": "lg-int", "topic": "langgraph", "tags": "interrupt command resume thread checkpointer re-execute",
     "fact": "LangGraph interrupt(payload) raises GraphInterrupt, persists state, waits. Resume with same thread_id and Command(resume=value). Value becomes interrupt() return. The node restarts from the beginning — never put irreversible work before interrupt. Multiple interrupts in one node match resume values by order. Requires a checkpointer."},
    {"id": "lg-ck", "topic": "langgraph", "tags": "checkpoint thread store versions_seen channel_versions",
     "fact": "Checkpointer = short-term thread snapshots (HITL, time travel). Store = long-term cross-thread facts. Checkpoint fields: id, parent, channel_values, channel_versions, versions_seen, pending writes. InMemorySaver dies on restart; Postgres is production. Resume without the same thread_id starts a new graph."},
    {"id": "lg-red", "topic": "langgraph", "tags": "reducer add_messages overwrite operator.add",
     "fact": "Reducer: new = reducer(old, update). Default overwrite. operator.add appends. Parallel node writes need an associative reducer or one write wins."},
    {"id": "lg-add", "topic": "langgraph", "tags": "add_messages messagesstate id upsert removemessage",
     "fact": "add_messages upserts by message id: new id appends, same id replaces, RemoveMessage deletes. MessagesState is list[AnyMessage] with this reducer. Same text + different ids = two rows. Use this so interrupt resume does not duplicate assistant messages."},
    {"id": "lg-dec", "topic": "langgraph", "tags": "approve edit reject respond interrupt_on tool",
     "fact": "Tool HITL interrupt_on decisions: approve (run as-is), edit (change args), reject (feedback), respond (answer agent without running the tool)."},
    {"id": "ov-cap", "topic": "oversight", "tags": "pele capacity bottleneck human loop",
     "fact": "Oversight Has a Capacity (arXiv:2606.08919): human review is the scarce resource. Batch, prioritize, or auto-allow low-risk actions. Farnaz pele counter is a local reminder, not the paper's math."},
    {"id": "xai-key", "topic": "xai", "tags": "api key grok-4.6 chat completions xai-",
     "fact": "Live Grok needs a key from console.x.ai starting with xai-. UUID keys are rejected. Endpoint https://api.x.ai/v1/chat/completions, model grok-4.6. Context 500k. Offline Farnaz does not call this."},
    {"id": "fa-lock", "topic": "farnaz", "tags": "lock chatgpt 8765 local_agent",
     "fact": "Farnaz must never read, write, or start the original ChatGPT agent under apps/local_agent on port 8765."},
]


def list_sources(topic: str | None = None) -> str:
    rows = SOURCES
    if topic:
        t = topic.lower().strip()
        rows = [s for s in SOURCES if t in s["topic"] or t in s["title"].lower()]
    if not rows:
        rows = SOURCES
    lines = [f"Farnaz sources ({len(rows)} of {len(SOURCES)} curated; not the whole web)"]
    for s in rows:
        lines.append(f"[{s['topic']}] {s['title']}\n{s['url']}")
    return "\n\n".join(lines)
