tunnel: 7d99d6ab-0a15-4f79-89d5-95e1fc48b773

credentials-file: C:\Users\sohei\.cloudflared\7d99d6ab-0a15-4f79-89d5-95e1fc48b773.json

ingress:
  - hostname: agent.warlock-plugins.com
    service: http://127.0.0.1:8780

  - service: http_status:404